# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Avoid' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'
  pod 'BarcodeScanner'

  target 'AvoidTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'AvoidUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
